### ISSUE TITLE
interleaved binary data support

### ISSUE THREAD

**Issue by lucaszanella** [sdroege/rtsp-types#5]
Hello, I'm willing to contribute to this library. I'm writing software that receives video from cameras. Currently I call a C++ RTSP library from Rust.

I'd like to know if there's support for binary interleaved RTP messages in RTSP. If not, I can add support for it. 

Do you have a client example that I can begin with? I understand that the library is just a parser but if there's a client example for me to test it'd be much faster for my development

**Comment by sdroege** [comment]
Interleaved binary messages are supported via [`Message::Data`](https://github.com/sdroege/rtsp-types/blob/3c31a3963a4b3d1337aadcaed3ebf99f000c0a95/src/message.rs#L23).

I'm writing an RTSP server around this. You can find an initial version [here](https://github.com/sdroege/rtsp-server) but there's still a lot more work to do. It's mostly in construction at this point :)

**Comment by lucaszanella** [comment]
@sdroege I took a look at this but I didn't read much and I thoguht you were using gstreamer to stream RTSP as it's in the dependencies.

I'm looking to create a client. Guess I'll have to write one myself then, but very nice that it already has support for interleaved binary data :)

**Comment by sdroege** [comment]
Writing a client on top of this should be relatively simple too. If you're doing it async, feel free to take [this](https://github.com/sdroege/rtsp-server/blob/master/src/listener/message_socket.rs).

Also let me know if you run into any problems or find bugs

**Comment by sdroege** [comment]
> but the state machines for client and server need to be implemented.

See the link I sent above for the server state machine, or big parts of it at least.

> It needs to be hidden because, correct if I'm wrong, we receive the nonce for hashing just after sending a `DESCRIBE`. However, to send a `DESCRIBE`, currently it serializes the url with credentials.

That's something for the client to implement. You would first send an URI without credentials, and if you get "not authorized" back you would take care of sending the credentials. That has nothing to do with using the `uri` crate or not :)

Note that some servers also require credentials only starting at `SETUP` or already for an initial `OPTIONS`.

> Wouldn't it be better to copy https://github.com/sgodwincs/rtsp-rs/blob/19205ae9af24d8a837b2bf112db90320165e6f5d/rtsp-2/src/uri/request.rs?

I'd prefer to not implement my own URI parser as that's not exactly trivial to get right. Copying some other implementation in is even worse than just depending on a widely used one.

> I'd remove `lazy_static` from his implementation too, I like very very minimal dependencies for security. What you think of this?

That makes no sense to me. `lazy_static` is very widely used and where it's used is completely irrelevant for security aspects too. It would however make sense to instead use `once_cell` because that API has moved into `std` already and will be stabilized at some point.
